-- DDL for palpites_gerados table
-- Stores predictions generated by AI / platform and recommendations/abstenctions for games

USE `footballweb`;

CREATE TABLE IF NOT EXISTS `palpites_gerados` (
  `id_palpite` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `fixture_id` INT NOT NULL,
  `home_team` VARCHAR(100) NULL DEFAULT NULL,
  `away_team` VARCHAR(100) NULL DEFAULT NULL,
  `mercado` VARCHAR(100) NOT NULL DEFAULT 'Total de Cartões',
  `linha_sugerida` VARCHAR(150) NOT NULL,
  `odd_momento` DECIMAL(5,2) NULL DEFAULT NULL,
  `resultado_status` ENUM('GREEN', 'RED', 'VOID', 'NO_BET', 'PENDING') NOT NULL DEFAULT 'PENDING',
  `detalhe_resultado` VARCHAR(255) NULL DEFAULT NULL,
  `criado_em` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_fixture_id` (`fixture_id`),
  INDEX `idx_resultado_status` (`resultado_status`),
  INDEX `idx_mercado` (`mercado`),
  CONSTRAINT `fk_palpites_fixture` FOREIGN KEY (`fixture_id`) REFERENCES `fixtures_trends` (`fixture_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
